config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'welcome/index'
  resources "entries"

  resources "sites", only: [:index, :new, :create]

  resources "comments"

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	has_many :comments
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def create
    comment_params = params["comment"].permit("content", "author", "email", "entry_id")
    comment = Comment.create(comment_params)
    redirect_to(entry_path(params["comment"]["entry_id"]))
  end

  def edit
    @comment = Comment.find(params["id"])
  end

  def update
    comment_params = params["comment"].permit("content", "author", "email", "entry_id")
    comment = Comment.find(params["id"])
    comment.update(comment_params)
    redirect_to(entry_path(params["comment"]["entry_id"]))
  end

  def destroy
    comment = Comment.find(params["id"])
    comment.destroy
    redirect_to(entries_path)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index 
		@websites = [
		    ["http://railsgirls.com", "Rails Girls"],
		    ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
		    ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
	  	]

	  @entries = Entry.all
	end

	def show
		@entry = Entry.find(params["id"])
	end

	def new 
		@entry = Entry.new
	end

	def create
		entry_params = params["entry"].permit("title", "contents", "date")
  		entry = Entry.create(entry_params)
  		redirect_to(entry_path(entry))
	end

	def edit
	   @entry = Entry.find(params["id"])
	end

	def update
	   entry_params = params["entry"].permit("title", "contents", "date")
	   entry = Entry.find(params["id"])
	   entry.update(entry_params)
	   redirect_to(entry_path(entry))
	end

	def destroy
		entry = Entry.find(params["id"])
		entry.destroy
		redirect_to(entries_path)
	end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
  	@sites = Site.all
  end

  def new
  	@site = Site.new
  end

  def create
  	site_params = params["site"].permit("name", "url")
  	site = Site.create(site_params)
  	redirect_to(sites_path)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def contact
  	end
  	
  	def about
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  @websites = [
	    ["http://railsgirls.com", "Rails Girls"],
	    ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
	    ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
	  ]

	  @entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |form| %>
	<p><%= form.label("content") %></p>
	<p><%= form.text_area("content") %></p>
	<p><%= form.label("author") %></p>
	<p><%= form.text_field("author") %></p>
	<p><%= form.label("email") %></p>
	<p><%= form.text_field("email") %></p>
	<p><%= form.hidden_field :entry_id, :value => entry_id %></p>
	<p><%= form.submit %></p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Edytuj komentarz</h1>
<%= render partial: 'form', locals: {comment: @comment, entry_id: @comment.entry.id} %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/entries/_form.html.erb
<%= form_for(entry) do |form| %>
	<p><%= form.label("title") %></p>
	<p><%= form.text_field("title") %></p>
	<p><%= form.label("contents") %></p>
	<p><%= form.text_area("contents") %></p>
	<p><%= form.label("date") %></p>
	<p><%= form.date_field("date") %></p>
	<p><%= form.submit %></p>
<% end %>

app/views/entries/edit.html.erb
<%= render partial:'form', locals: {entry: @entry} %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
  <div>
  	<% for entry in @entries %>
  		<h2><%= link_to(entry.title, entry_path(entry)) %></h2>
  		<p><%= entry.date %></p>
  		<p><%= entry.contents %></p>
      <ul>
        <li><%= link_to("Edit this entry", edit_entry_path(entry)) %></li>
        <li><%= link_to("Delete", entry_path(entry), data: {confirm: "Are you sure?"}, method: :delete) %></li>
      </ul>
  	<% end %>
  </div>
  <div>
    <br>
  	<%= link_to("New entry", new_entry_path) %>

  </div>

app/views/entries/new.html.erb
<%= render partial: 'form', locals: {entry: @entry} %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
	<p><%= @entry.date %></p>
	<p><%= @entry.contents %></p>
	<% if @entry.comments.any? %>
		<div class="comment">
			<h4>Comments (<%= @entry.comments.size %>)</h4>
			<ul>
				<% for comment in @entry.comments %>
		  			<li class="col-md-12"><%= comment.content %></li>
		  			<li class="comment_authorship">Added by <b><%= comment.author %></b></li>
		  			<li class="comment_authorship"><%= comment.email %></li>
		  			<li class="comment_authorship"><%= link_to("Edit", edit_comment_path(comment)) %></li>
		  			<li class="comment_authorship"><%= link_to("Delete", comment_path(comment), data: {confirm: "Are you sure?"}, method: :delete) %></li>
		  		<% end %>
		  	</ul>
		</div>
		<% else %>
		<div class="comment">
			<h4>No comments</h4>
		</div>
	<% end %>

	<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
	<p><%= link_to("Back to all entries", entries_path) %></p>

	<%= render partial: 'comments/form', locals: {comment: Comment.new, entry_id: @entry.id} %>

app/views/includes/_head.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Alegreya" rel="stylesheet">
</head>

app/views/includes/_header.html.erb
<header class="header">
  <nav class="navbar navbar-default col-md-12">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header navbar-left col-md-6">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <h1><%= link_to "My Rails Girls Diary", welcome_index_path %></h1>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right col-md-6" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Blog", entries_path %></li>
          <li><%= link_to "Websites", sites_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Info <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "About me", static_pages_about_path %></li>
              <li><%= link_to "Contact", static_pages_contact_path %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<%= render "includes/head.html.erb" %>
<div class="container-fluid">
	<body>
	<%= render "includes/header.html.erb" %>
	<div class="main">
	<%= yield %>
	</div>
	</body>
</div>
</html>

app/views/sites/_form.html.erb
<%= form_for(site) do |form| %>
	<p><%= form.label("name") %></p>
	<p><%= form.text_field("name") %></p>
	<p><%= form.label("url") %></p>
	<p><%= form.text_area("url") %></p>
	<p><%= form.submit %></p>
<% end %>

app/views/sites/create.html.erb
<h1>Sites#create</h1>
<p>Find me in app/views/sites/create.html.erb</p>

app/views/sites/index.html.erb
<h1>My favourite websites</h1>
<div>
  	<% for site in @sites %>
  		<h2><%= site.name %></h2>
  		<p><%= link_to(site.url, site.url) %></p>
  	<% end %>
  </div>
  <div>
    <br>
  	<%= link_to("New site", new_site_path) %>

  </div>

app/views/sites/new.html.erb
<%= render partial: 'form', locals: {site: @site} %>
<p><%= link_to("Back to all entries", sites_path) %></p>

app/views/static_pages/about.html.erb
<h1>About me</h1>
<p>My name is Joanna, I am a student of last year of Translation Studies and Electronic Information Processing. I like sci-fi, running, books of all kinds and weird music. One day I will run a marathon inside the Arctic Circle and sleep in a tent on Kamchatka. </p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>You can contact me at <a href=https://twitter.com/jbyszuk>twitter</a>.</p>

app/views/welcome/index.html.erb
  <div>
    <p class="intro">This is a website dedicated to documenting my Rails Girls workshop experience.</p>
    <img src="http://railsgirls.com/images/rg-warsaw.png" />
  </div>